name: dart_console
version: 1.1.0
homepage: https://github.com/timsneath/dart_console
description: 
  A helper library for command-line applications that need more control over input/output than the standard library provides.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: '>=1.0.0 <3.0.0'
  win32: ^2.6.1
  intl: ^0.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.3
